import { useEffect, useMemo, useState } from 'react';
import { RoleSwitch } from './components/RoleSwitch';
import { addShareholder, adjustMemberFunding, adjustOwnRatio, completeInitialFundingSetup, createMockRound, demoActor, deriveMemberDashboard, mockWorkspace, moveRoundToTrash, normalizeWorkspace, permanentlyDeleteRound, restoreRound, reviewReturnRequest, saveMemberSummary, setShareholderActive, settleMockRound, submitReturnRequest, workspaceForActor } from './data/mock';
import type { FundingChangeInput, OpeningFundingInput } from './data/mock';
import type { MemberDashboard, Workspace } from './data/types';
import { AssetsPage } from './pages/AssetsPage';
import { HomePage } from './pages/HomePage';
import { LedgerPage } from './pages/LedgerPage';

type Tab = 'home' | 'assets' | 'ledger';
const workspaceKey = 'pybit-demo-v2-workspace'; const memberKey = 'pybit-demo-v2-member'; const legacyKey = 'pybit-workspace';
const backup = (key: string, value: string) => localStorage.setItem(`pybit-demo-v2-backup-${Date.now()}-${key}`, value);
const loadWorkspace = (): Workspace => {
  try { const current = localStorage.getItem(workspaceKey); if (current) return normalizeWorkspace(JSON.parse(current) as Workspace); const legacy = localStorage.getItem(legacyKey); if (legacy) { backup('legacy-workspace', legacy); const migrated = normalizeWorkspace(JSON.parse(legacy) as Workspace); localStorage.setItem(workspaceKey, JSON.stringify(migrated)); return migrated; } }
  catch (error) { console.error('PyBit demo migration failed', error); throw new Error('演示数据无法安全迁移，原始数据未被覆盖。请先导出备份。'); }
  return structuredClone(mockWorkspace);
};

export default function DemoApp() {
  const [tab, setTab] = useState<Tab>('home'); const [workspace, setWorkspace] = useState<Workspace>(loadWorkspace); const [memberId, setMemberId] = useState(() => localStorage.getItem(memberKey) || 'member-b'); const [clockTick, setClockTick] = useState(0); const [updateReady, setUpdateReady] = useState(false);
  const safeMemberId = workspace.members.some((member) => member.id === memberId && member.active !== false) ? memberId : workspace.members.find((member) => member.active !== false)?.id ?? '';
  const actor = useMemo(() => safeMemberId ? demoActor(safeMemberId) : null, [safeMemberId]); const visibleWorkspace = useMemo(() => actor ? workspaceForActor(workspace, actor) : workspace, [workspace, actor]); const dashboard = useMemo<MemberDashboard | null>(() => actor ? deriveMemberDashboard(workspace, actor.memberId) : null, [workspace, actor, clockTick]);
  useEffect(() => { localStorage.setItem(workspaceKey, JSON.stringify(workspace)); }, [workspace]);
  useEffect(() => { if (safeMemberId) { if (safeMemberId !== memberId) setMemberId(safeMemberId); localStorage.setItem(memberKey, safeMemberId); } }, [memberId, safeMemberId]);
  useEffect(() => { const timer = window.setInterval(() => setClockTick((value) => value + 1), 30_000); return () => window.clearInterval(timer); }, []);
  useEffect(() => { const handler = () => setUpdateReady(true); window.addEventListener('pybit-update-ready', handler); return () => window.removeEventListener('pybit-update-ready', handler); }, []);
  if (!actor || !dashboard) return <main className="locked-page"><section className="panel"><p className="field-error">演示成员资料无效，请从恢复页导出备份。</p></section></main>;
  const settle = (roundId: string, grossResultCents: number) => setWorkspace((current) => settleMockRound(current, actor, roundId, grossResultCents)); const createRound = (scheduledDate: string, totalStakeCents: number) => setWorkspace((current) => createMockRound(current, actor, scheduledDate, totalStakeCents)); const trash = (roundId: string, reason: string) => setWorkspace((current) => moveRoundToTrash(current, actor, roundId, reason)); const restore = (roundId: string) => setWorkspace((current) => restoreRound(current, actor, roundId)); const purge = (roundId: string, typedName: string) => setWorkspace((current) => permanentlyDeleteRound(current, actor, roundId, typedName)); const ratio = (deltaBps: number) => setWorkspace((current) => adjustOwnRatio(current, actor, deltaBps)); const requestReturn = (amountCents: number, idempotencyKey: string) => setWorkspace((current) => submitReturnRequest(current, actor, amountCents, idempotencyKey)); const reviewReturn = (id: string, approved: boolean, reason?: string) => setWorkspace((current) => reviewReturnRequest(current, actor, id, approved, reason)); const openingFunding = (entries: OpeningFundingInput[]) => setWorkspace((current) => completeInitialFundingSetup(current, actor, entries)); const fundingChange = (targetMemberId: string, input: FundingChangeInput) => setWorkspace((current) => adjustMemberFunding(current, actor, targetMemberId, input)); const memberSummary = (targetMemberId: string, input: { name: string; principalCents: number; ratioBps?: number }) => setWorkspace((current) => saveMemberSummary(current, actor, targetMemberId, input)); const addMember = () => setWorkspace((current) => addShareholder(current, actor)); const memberActive = (targetMemberId: string, active: boolean) => setWorkspace((current) => setShareholderActive(current, actor, targetMemberId, active));
  const resetDemo = () => { if (!window.confirm('确认重置演示数据？当前演示数据会先保留一份本地备份。')) return; const current = localStorage.getItem(workspaceKey); if (current) backup('before-reset', current); setWorkspace(structuredClone(mockWorkspace)); setMemberId('member-b'); setTab('home'); };
  const pending = dashboard.member.isCzh ? workspace.returnRequests.filter((request) => request.status === 'pending').length : 0;
  return <div className="app-shell">{updateReady && <p className="notice toast-notice">新版本可用 <button className="chip" onClick={() => navigator.serviceWorker.getRegistration().then((registration) => registration?.waiting?.postMessage('PYBIT_ACTIVATE_UPDATE'))}>点击更新</button></p>}<header><div><div className="brand">PY<span>BIT</span></div><div className="demo-mark">演示数据 · 本地模拟身份不构成真实认证</div></div><div className="role-label">{dashboard.member.isCzh ? '主要管理员' : dashboard.member.role === 'ADMIN' ? '备用管理员' : '成员'}</div><button className="chip" onClick={resetDemo}>重置演示数据</button></header><RoleSwitch members={workspace.members.filter((member) => member.active !== false)} activeId={safeMemberId} onChange={setMemberId} />{tab === 'home' && <HomePage dashboard={dashboard} />}{tab === 'assets' && <AssetsPage dashboard={dashboard} workspace={visibleWorkspace} onRatio={ratio} onReturn={requestReturn} />}{tab === 'ledger' && <LedgerPage dashboard={dashboard} workspace={visibleWorkspace} onSettle={settle} onCreate={createRound} onTrash={trash} onRestore={restore} onPurge={purge} onReviewReturn={reviewReturn} onOpeningFunding={openingFunding} onFundingChange={fundingChange} onMemberSummary={memberSummary} onAddMember={addMember} onMemberActive={memberActive} />}<nav className="bottom-nav"><button className={tab === 'home' ? 'active' : ''} onClick={() => setTab('home')}>收益</button><button className={tab === 'assets' ? 'active' : ''} onClick={() => setTab('assets')}>资产</button><button className={tab === 'ledger' ? 'active' : ''} onClick={() => setTab('ledger')}>账本{pending > 0 && <i className="badge">{pending}</i>}</button></nav></div>;
}
