import { useEffect, useRef, useState } from 'react';
import { MetricCard } from '../components/MetricCard';
import { czhRatioBps } from '../data/mock';
import type { MemberDashboard, Workspace } from '../data/types';
import { formatB, formatPercent, parseBToCents } from '../domain/ledger';

export function AssetsPage({ dashboard, workspace, onRatio, onReturn }: { dashboard: MemberDashboard; workspace: Workspace; onRatio: (bps: number) => void; onReturn: (cents: number, idempotencyKey: string) => void }) {
  const draftKey = `pybit-demo-draft-assets-${dashboard.member.id}`; const saved = (() => { try { return JSON.parse(sessionStorage.getItem(draftKey) || '{}') as { add?: string; reduce?: string; returnInput?: string }; } catch { return {}; } })();
  const [add, setAdd] = useState(saved.add ?? ''); const [reduce, setReduce] = useState(saved.reduce ?? ''); const [returnInput, setReturnInput] = useState(saved.returnInput ?? ''); const [notice, setNotice] = useState(''); const [ratioError, setRatioError] = useState(''); const [returnError, setReturnError] = useState(''); const [allRequests, setAllRequests] = useState(false);
  const returnKey = useRef<string | null>(null);
  const reserved = workspace.returnRequests.filter((request) => request.memberId === dashboard.member.id && request.status === 'pending').reduce((sum, request) => sum + request.amountCents, 0); const availableReturn = dashboard.pendingReturnCents - reserved;
  useEffect(() => { sessionStorage.setItem(draftKey, JSON.stringify({ add, reduce, returnInput })); }, [draftKey, add, reduce, returnInput]);
  const ratioAction = (value: string, sign: 1 | -1) => { setRatioError(''); const points = Number(value); const bps = Math.round(points * 100) * sign; if (!Number.isFinite(points) || points <= 0 || !Number.isInteger(points * 100)) return setRatioError('请输入大于0、最多两位小数的百分点。'); if (sign > 0 && bps > czhRatioBps(workspace)) return setRatioError(`当前最多可加仓${formatPercent(czhRatioBps(workspace))}。`); if (sign < 0 && -bps > dashboard.member.ratioBps) return setRatioError(`当前最多可减仓${formatPercent(dashboard.member.ratioBps)}。`); try { onRatio(bps); setNotice(sign > 0 ? '下场参与比例已提高。' : '下场参与比例已降低。'); sign > 0 ? setAdd('') : setReduce(''); } catch { setRatioError('比例调整失败，请稍后重试。'); } };
  const submitReturn = () => { setReturnError(''); const cents = parseBToCents(returnInput); if (cents === null || cents <= 0 || cents > availableReturn) return setReturnError(`可申请转回金额为${formatB(availableReturn)}。`); try { returnKey.current ??= globalThis.crypto?.randomUUID?.() ?? `return-${Date.now()}`; onReturn(cents, returnKey.current); setReturnInput(''); returnKey.current = null; setNotice('转回申请已提交，等待czh处理。'); } catch { setReturnError('转回申请失败，请稍后重试。'); } };
  const mine = workspace.returnRequests.filter((request) => request.memberId === dashboard.member.id); const visibleRequests = (allRequests ? mine : mine.slice(-3)).slice().reverse(); const currentRatio = dashboard.member.isCzh ? czhRatioBps(workspace) : dashboard.member.ratioBps;
  return <main className="page"><h1>我的资产</h1><MetricCard label="当前投资余额" value={formatB(dashboard.investmentAssetCents)} hint={`可用 ${formatB(dashboard.availableInvestmentCents)} · 场次中已投入 ${formatB(dashboard.lockedRoundCostCents)}`} /><div className="two-grid"><MetricCard label="账上待转回余额" value={formatB(dashboard.pendingReturnCents)} hint="确认前不参加后续场次" /><MetricCard label="已经实际转回余额" value={formatB(dashboard.returnedCents)} hint="历史实际转回" /></div>
    <section className="panel"><h2>调整下场参与比例</h2><p>我的比例：<b>{formatPercent(currentRatio)}</b> {add && !dashboard.member.isCzh ? `→ ${formatPercent(currentRatio + Math.round(Number(add || 0) * 100))}` : ''}</p>{dashboard.member.isCzh ? <p className="hint">czh比例由其他成员参与比例自动补足。</p> : <><p className="hint">CZH剩余比例：{formatPercent(czhRatioBps(workspace))} · 当前最多可加仓{formatPercent(czhRatioBps(workspace))}。调整只改变后续每场投入，不会自动将账户资金转回。</p><label className="input-label">加仓（百分点）<input value={add} inputMode="decimal" onChange={(e) => setAdd(e.target.value)} placeholder="例如 5" /></label><button className="primary-button" onClick={() => ratioAction(add, 1)}>提高比例</button><label className="input-label">减仓（百分点）<input value={reduce} inputMode="decimal" onChange={(e) => setReduce(e.target.value)} placeholder="例如 5" /></label><button className="chip" onClick={() => ratioAction(reduce, -1)}>降低比例</button>{ratioError && <p className="field-error">{ratioError}</p>}</>}</section>
    <section className="panel"><h2>取回资金</h2><p className="hint">① czh将可退出金额转入待转回；② 成员提交转回申请；③ czh实际转回后确认完成。</p>{availableReturn === 0 && <p className="hint">暂无可申请转回的余额，请联系czh将需要取回的资金转入待转回。</p>}<p className="hint">可申请转回金额：{formatB(availableReturn)}</p><label className="input-label">转回金额 B<input value={returnInput} inputMode="decimal" onChange={(e) => setReturnInput(e.target.value)} placeholder="例如 B3,000.00" /></label>{returnError && <p className="field-error">{returnError}</p>}<button className="primary-button" onClick={submitReturn}>提交申请</button><div className="section-heading"><h2>申请记录</h2>{mine.length > 3 && <button className="chip" onClick={() => setAllRequests((shown) => !shown)}>{allRequests ? '收起' : '查看全部'}</button>}</div>{visibleRequests.map((request) => <p className="hint" key={request.id}>{formatB(request.amountCents)} · 申请 {request.createdAt} · {request.status === 'pending' ? '待处理' : request.status === 'approved' ? `已实际转回 · ${request.reviewedAt}` : request.status === 'needs_review' ? `待核对：${request.reviewBlockReason}` : `已拒绝${request.reviewedAt ? ` · ${request.reviewedAt}` : ''}${request.rejectReason ? ` · 原因：${request.rejectReason}` : ' · 请联系czh了解原因'}`}</p>)}</section>{notice && <p className="notice toast-notice">{notice}</p>}
  </main>;
}
