import { useEffect, useState } from 'react';
import type { MatchInput, MemberDashboard, ReturnRequest, SettledMemberRound, Workspace } from '../data/types';
import { formatB, formatPercent, parseBToCents, tone } from '../domain/ledger';
import { deriveMemberDashboard, roundName } from '../data/mock';
import type { FundingChangeInput, OpeningFundingInput } from '../data/mock';

type Props = {
  dashboard: MemberDashboard; workspace: Workspace; shares: Record<string, number>; onSettle: (roundId: string, grossResultCents: number) => void;
  onCreate: (scheduledDate: string, totalStakeCents: number) => void;
  onTrash: (roundId: string, reason: string) => void; onRestore: (roundId: string) => void; onPurge: (roundId: string, typedName: string) => void; onReviewReturn: (id: string, approved: boolean, reason?: string) => void;
  onOpeningFunding: (entries: OpeningFundingInput[]) => void; onFundingChange: (memberId: string, input: FundingChangeInput) => void;
  onMemberSummary: (memberId: string, input: { name: string; principalCents: number }) => void; onAddMember: () => void; onMemberActive: (memberId: string, active: boolean) => void;
};

type OpeningForm = { deposit: string; investment: string };
type AdjustmentForm = { type: FundingChangeInput['type']; value: string; reason: string; effectiveAt: string };

export function LedgerPage({ dashboard, workspace, shares, onSettle, onCreate, onTrash, onRestore, onPurge, onReviewReturn, onOpeningFunding, onFundingChange, onMemberSummary, onAddMember, onMemberActive }: Props) {
  const [notice, setNotice] = useState(''); const [grossInput, setGrossInput] = useState(''); const [showTrash, setShowTrash] = useState(false);
  const [undoRound, setUndoRound] = useState<SettledMemberRound | null>(null); const [purgeTarget, setPurgeTarget] = useState<MatchInput | null>(null); const [typedName, setTypedName] = useState('');
  const [opening, setOpening] = useState<Record<string, OpeningForm>>(() => Object.fromEntries(workspace.members.map((member) => [member.id, { deposit: (member.initialDepositCents / 100).toFixed(2), investment: (member.initialInvestmentCents / 100).toFixed(2) }])));
  const [editingMemberId, setEditingMemberId] = useState<string | null>(null); const [adjustment, setAdjustment] = useState<AdjustmentForm>({ type: 'DEPOSIT', value: '', reason: '', effectiveAt: '2026-09-09T00:00' });
  const [showCreate, setShowCreate] = useState(false); const [createDate, setCreateDate] = useState(() => new Intl.DateTimeFormat('sv-SE', { timeZone: 'Asia/Shanghai', dateStyle: 'short' }).format(new Date())); const [createStake, setCreateStake] = useState('1000.00'); const [createError, setCreateError] = useState(''); const [grossError, setGrossError] = useState('');
  const [summaryDrafts, setSummaryDrafts] = useState<Record<string, { name: string; principal: string }>>({}); const [summaryError, setSummaryError] = useState<Record<string, string>>({}); const [rejectTarget, setRejectTarget] = useState<ReturnRequest | null>(null); const [rejectReason, setRejectReason] = useState('');
  const isAdmin = dashboard.member.role === 'ADMIN'; const trashedRounds = workspace.rounds.filter((round) => round.status === 'deleted');
  useEffect(() => { if (!undoRound) return; const timer = window.setTimeout(() => setUndoRound(null), 5000); return () => window.clearTimeout(timer); }, [undoRound]);
  useEffect(() => { if (!notice) return; const timer = window.setTimeout(() => setNotice(''), 5000); return () => window.clearTimeout(timer); }, [notice]);
  const createPreview = (() => { const sequence = (workspace.sequenceReservations[createDate] ?? 0) + 1; return /^\d{4}-\d{2}-\d{2}$/.test(createDate) ? roundName({ id: 'preview', label: '', scheduledDate: createDate, timezone: 'Asia/Shanghai', sequence, occurredAt: '', totalStakeCents: 0, status: 'OPEN' }) : '请填写日期'; })();
  const create = () => { setCreateError(''); const cents = parseBToCents(createStake); if (!/^\d{4}-\d{2}-\d{2}$/.test(createDate) || cents === null || cents <= 0) { setCreateError('请输入有效日期和大于0的总投入金额，例如 B1,000.00。'); return; } try { onCreate(createDate, cents); setShowCreate(false); setNotice(`已创建${createPreview}，各成员投入已按可用余额占比锁定。`); } catch (error) { setCreateError(error instanceof Error && error.message === 'INSUFFICIENT_INVESTMENT' ? '成员可用投资余额合计不足，场次未创建。' : '请检查金额。'); } };
  const settle = (roundId: string) => { setGrossError(''); const grossResultCents = parseBToCents(grossInput); if (grossResultCents === null) { setGrossError('请输入毛结束金额，可填写 0、3000、3,000.00 或 B3,000.00。'); return; } onSettle(roundId, grossResultCents); setGrossInput(''); setNotice('本场次已正式结算；手续费、抽水、结束所得、资产变动和收益率已按规则计算。'); };
  const confirmPurge = () => { if (!purgeTarget || typedName !== roundName(purgeTarget)) { setNotice('请输入完整且完全一致的场次名称。'); return; } onPurge(purgeTarget.id, typedName); setNotice('该场次已永久删除；保留了不含金额的管理员审计记录。'); setPurgeTarget(null); setTypedName(''); };
  const settledRounds = dashboard.rounds.filter((round): round is SettledMemberRound => round.status === 'SETTLED').slice().reverse();
  const pendingRequests = workspace.returnRequests.filter((request) => request.status === 'requested');
  const transferredRequests = workspace.returnRequests.filter((request) => request.status === 'transferred');
  const blockedRequests = workspace.returnRequests.filter((request) => request.status === 'needs_review');
  const shanghaiNow = new Intl.DateTimeFormat('sv-SE', { timeZone: 'Asia/Shanghai', dateStyle: 'short', timeStyle: 'medium', hour12: false }).format(new Date()).replace(',', '');
  const pendingFunding = workspace.fundingAdjustments.filter((adjustment) => adjustment.type !== 'OPENING_IMPORT' && adjustment.effectiveAt > shanghaiNow);
  const updateOpening = (id: string, field: keyof OpeningForm, value: string) => setOpening((current) => ({ ...current, [id]: { ...current[id], [field]: value } }));
  const saveOpening = () => {
    const entries: OpeningFundingInput[] = workspace.members.map((member) => ({ memberId: member.id, depositCents: parseBToCents(opening[member.id]?.deposit ?? '') ?? -1, investmentCents: parseBToCents(opening[member.id]?.investment ?? '') ?? -1 }));
    if (entries.some((entry) => entry.depositCents < 0 || entry.investmentCents < 0)) { setNotice('请检查金额：金额不能为负数。'); return; }
    try { onOpeningFunding(entries); setNotice('期初录入已保存，并已生成全部成员的期初录入流水。'); } catch { setNotice('期初录入失败，请检查金额。'); }
  };
  const submitAdjustment = (memberId: string) => {
    const selected = workspace.members.find((member) => member.id === memberId)!;
    if (!adjustment.reason.trim() || !adjustment.effectiveAt) { setNotice('请填写调整原因和生效时间。'); return; }
    const input: FundingChangeInput = { type: adjustment.type, reason: adjustment.reason, effectiveAt: adjustment.effectiveAt.replace('T', ' ') };
    const cents = parseBToCents(adjustment.value); if (cents === null || (adjustment.type !== 'BALANCE_CORRECTION' && cents <= 0)) { setNotice('请输入有效的非负金额；增加入金和转入待转回必须大于0。'); return; }
    if (adjustment.type === 'BALANCE_CORRECTION') input.targetCents = cents; else input.amountCents = cents;
    try { onFundingChange(memberId, input); setNotice(`${selected.name}的资金配置已保存，并已留下调整流水。`); setEditingMemberId(null); setAdjustment({ type: 'DEPOSIT', value: '', reason: '', effectiveAt: '2026-09-09T00:00' }); } catch { setNotice('调整失败：请确认金额、可用投资余额和权限。'); }
  };
  // Dashboards must always be derived from the FULL workspace; the member's own row reuses the prop
  // because the role-filtered workspace cannot replay round allocations on its own.
  const rowDashboard = (memberId: string) => memberId === dashboard.member.id ? dashboard : deriveMemberDashboard(workspace, memberId);
  const draftFor = (memberId: string) => summaryDrafts[memberId] ?? (() => { const member = workspace.members.find((row) => row.id === memberId)!; return { name: member.name, principal: (rowDashboard(memberId).confirmedDepositCents / 100).toFixed(2) }; })();
  const saveSummary = (memberId: string) => { const member = workspace.members.find((row) => row.id === memberId)!; const draft = draftFor(memberId); const principal = parseBToCents(draft.principal); if (principal === null || principal < 0) { setSummaryError((current) => ({ ...current, [memberId]: '请输入非负金额。' })); return; } try { onMemberSummary(memberId, { name: draft.name, principalCents: principal }); setSummaryError((current) => ({ ...current, [memberId]: '' })); setNotice(`${draft.name}的累计投入已保存。`); } catch (error) { setSummaryError((current) => ({ ...current, [memberId]: error instanceof Error && error.message === 'INSUFFICIENT_INVESTMENT' ? '本金减少不能占用进行中场次资金。' : '保存失败，请检查输入。' })); } };
  return <main className="page"><h1>{isAdmin ? '账本与管理' : '我的账本'}</h1><section className="panel"><p className="hint">每场次独立流水。普通成员仅看到自己的金额；管理员可切换身份预览全体口径。</p></section>
    {dashboard.member.isCzh && <section className="panel review-panel"><h2>取回处理</h2>{pendingRequests.length === 0 ? <p className="hint">暂无待确认转出的取回申请</p> : pendingRequests.map((request) => <div className="trash-row" key={request.id}><strong>{workspace.members.find((m) => m.id === request.memberId)?.name}</strong><div className="return-amount">{formatB(request.amountCents)}</div><p>申请 {request.createdAt} · 当前待转回 {formatB(deriveMemberDashboard(workspace, request.memberId).pendingReturnCents)}</p><button className="primary-button" onClick={() => onReviewReturn(request.id, true)}>已实际转出，确认转出</button><button className="danger-button" onClick={() => { setRejectTarget(request); setRejectReason(''); }}>拒绝</button></div>)}{transferredRequests.map((request) => <div className="trash-row" key={request.id}><strong>待成员确认收到 · {workspace.members.find((m) => m.id === request.memberId)?.name}</strong><div className="return-amount">{formatB(request.amountCents)}</div><p>czh已转出 {request.transferredAt}</p></div>)}{blockedRequests.map((request) => <div className="trash-row" key={request.id}><strong>待核对记录 · {workspace.members.find((m) => m.id === request.memberId)?.name}</strong><p>{formatB(request.amountCents)} · {request.reviewBlockReason}</p></div>)}</section>}
    {dashboard.member.isCzh && <section className="panel funding-panel"><div className="section-heading"><div><h2>成员管理</h2><p>这里只改累计投入，已有场次收益会保留；成员取回资金请在上方“取回处理”确认。</p></div><button className="chip" onClick={onAddMember}>添加股东</button></div><p className="hint">每场按各成员当前可用余额占全体可用余额的比例自动分摊，份额无需手动设置。</p>{workspace.members.filter((member) => member.active !== false).map((member) => { const draft = draftFor(member.id); const memberDashboard = rowDashboard(member.id); return <div className="funding-editor" key={member.id}><label className="input-label">成员名称<input value={draft.name} onChange={(event) => setSummaryDrafts((current) => ({ ...current, [member.id]: { ...draft, name: event.target.value } }))} /></label><label className="input-label">累计投入 B<input inputMode="decimal" value={draft.principal} onChange={(event) => setSummaryDrafts((current) => ({ ...current, [member.id]: { ...draft, principal: event.target.value } }))} /></label><p className="hint">当前投资余额 {formatB(memberDashboard.investmentAssetCents)} · 待转回 {formatB(memberDashboard.pendingReturnCents)} · 下场份额 {formatPercent(shares[member.id] ?? 0)}</p>{summaryError[member.id] && <p className="field-error">{summaryError[member.id]}</p>}<div className="trash-actions"><button className="chip" onClick={() => saveSummary(member.id)}>保存</button>{!member.isCzh && member.role !== 'ADMIN' && <button className="danger-button compact" onClick={() => { try { onMemberActive(member.id, false); setNotice(`已移出${member.name}。`); } catch (error) { setSummaryError((current) => ({ ...current, [member.id]: error instanceof Error && error.message === 'MEMBER_HAS_OPEN_ROUND' ? '该成员有进行中场次，请结算后再移出。' : error instanceof Error && error.message === 'MEMBER_HAS_PENDING_RETURN' ? '该成员有待处理转回申请，请先处理。' : '该成员仍有余额，请先转入待转回并完成转回。' })); } }}>移出</button>}</div></div>; })}<p className="hint">已移出成员：{workspace.members.filter((member) => member.active === false).map((member) => <button className="chip" key={member.id} onClick={() => onMemberActive(member.id, true)}>恢复 {member.name}</button>)}</p></section>}
    <section className="panel funding-panel"><div className="section-heading"><div><h2>成员资金配置</h2><p>{dashboard.member.isCzh ? '由CZH录入和调整；所有金额均以B展示，内部按整数分保存。' : '仅CZH可修改成员资金配置；当前为只读查看。'}</p></div><strong>{workspace.initialSetupComplete ? '已完成期初设置' : '待期初录入'}</strong></div>
      {!workspace.initialSetupComplete && dashboard.member.isCzh && <><p className="hint">首次保存会为所有成员建立“期初录入”流水；每场按可用余额占比自动分摊，无需设置比例。</p>{workspace.members.map((member) => <div className="funding-editor opening-editor" key={member.id}><strong>{member.name}</strong><label className="input-label">初始实际入金 B<input inputMode="decimal" value={opening[member.id]?.deposit ?? ''} onChange={(event) => updateOpening(member.id, 'deposit', event.target.value)} /></label><label className="input-label">初始投资余额 B<input inputMode="decimal" value={opening[member.id]?.investment ?? ''} onChange={(event) => updateOpening(member.id, 'investment', event.target.value)} /></label></div>)}<button className="primary-button" onClick={saveOpening}>保存期初录入</button></>}
      {(workspace.initialSetupComplete || !dashboard.member.isCzh) && <div className="funding-list">{workspace.members.map((member) => { const memberDashboard = rowDashboard(member.id); const editing = editingMemberId === member.id; return <article className="funding-row" key={member.id}><div className="section-heading"><strong>{member.name}</strong><span className="hint">下场份额按余额自动计算</span></div><div className="ledger-grid funding-grid"><span>累计实际入金<b>{formatB(memberDashboard.confirmedDepositCents)}</b></span><span>当前投资余额<b>{formatB(memberDashboard.investmentAssetCents)}</b></span><span>下场参与份额<b>{formatPercent(shares[member.id] ?? 0)}</b></span><span>待转回余额<b>{formatB(memberDashboard.pendingReturnCents)}</b></span><span>已实际转回<b>{formatB(memberDashboard.returnedCents)}</b></span></div>{dashboard.member.isCzh && <button className="chip" onClick={() => { setEditingMemberId(editing ? null : member.id); setAdjustment({ type: 'DEPOSIT', value: '', reason: '', effectiveAt: '2026-09-09T00:00' }); }}>{editing ? '收起调整' : '调整'}</button>}{editing && dashboard.member.isCzh && <div className="funding-editor"><label className="input-label">调整类型<select value={adjustment.type} onChange={(event) => setAdjustment((current) => ({ ...current, type: event.target.value as FundingChangeInput['type'], value: '' }))}><option value="DEPOSIT">增加实际入金</option><option value="TO_PENDING">减少投资余额并转入待转回</option><option value="BALANCE_CORRECTION">修正投资余额</option></select></label><label className="input-label">{adjustment.type === 'BALANCE_CORRECTION' ? '修正后的投资余额 B' : '调整金额 B'}<input inputMode="decimal" value={adjustment.value} onChange={(event) => setAdjustment((current) => ({ ...current, value: event.target.value }))} /></label><label className="input-label">调整原因<input value={adjustment.reason} onChange={(event) => setAdjustment((current) => ({ ...current, reason: event.target.value }))} placeholder="例如：补录入金" /></label><label className="input-label">生效时间<input type="datetime-local" value={adjustment.effectiveAt} onChange={(event) => setAdjustment((current) => ({ ...current, effectiveAt: event.target.value }))} /></label><button className="primary-button" onClick={() => submitAdjustment(member.id)}>保存调整</button></div>}</article>; })}</div>}
      {workspace.initialSetupComplete && dashboard.member.isCzh && <><p className="hint">最近调整流水：{workspace.fundingAdjustments.slice(-3).reverse().map((row) => `${workspace.members.find((member) => member.id === row.memberId)?.name}·${row.type}·${row.reason}`).join('；') || '暂无'}</p>{pendingFunding.length > 0 && <p className="hint">待生效：{pendingFunding.map((row) => `${workspace.members.find((member) => member.id === row.memberId)?.name}·${row.effectiveAt}`).join('；')}。生效前不会改变当前余额或可用额度。</p>}</>}</section>
    {isAdmin && <section className="panel admin-panel"><div className="section-heading"><h2>场次管理</h2><button className="chip" onClick={() => setShowTrash((shown) => !shown)}>回收站{trashedRounds.length ? `（${trashedRounds.length}）` : ''}</button></div><button className="primary-button" onClick={() => setShowCreate((shown) => !shown)}>{showCreate ? '收起新增场次' : '新增场次'}</button>{showCreate && <div className="funding-editor"><label className="input-label">场次日期（Asia/Shanghai）<input type="date" value={createDate} onChange={(event) => setCreateDate(event.target.value)} /></label><label className="input-label">总投入 B<input inputMode="decimal" value={createStake} onChange={(event) => setCreateStake(event.target.value)} /></label>{createError && <p className="field-error">{createError}</p>}<p className="hint">名称预览：{createPreview}。同日删除或永久删除的场次仍保留序号。</p><button className="primary-button" onClick={create}>保存场次</button></div>}<p className="hint">创建时按各成员当前可用余额占比自动分摊并锁定本金；可用余额合计不足则无法创建。</p></section>}
    {dashboard.openRounds.map((round) => <article className="panel ledger-row open-round" key={round.id}><div className="section-heading"><div><strong>{round.name}</strong><p>{round.occurredAt} · 场次进行中</p></div><strong className="neutral">进行中</strong></div><div className="ledger-grid single-row"><span>本场投入<b>{formatB(round.stakeCents)}</b></span></div>{isAdmin && <div className="settlement-form"><label className="input-label">本场毛结束金额 B<input inputMode="decimal" value={grossInput} onChange={(event) => setGrossInput(event.target.value)} placeholder="例如 B3,000.00" /></label>{grossError && <p className="field-error">{grossError}</p>}<p className="hint">毛结束金额：尚未扣手续费和抽水的结束金额。手续费为结束金额的3%；抽水为正毛利润的10%。</p><button className="primary-button" onClick={() => settle(round.id)}>确认结算</button></div>}</article>)}
    <div className="ledger-list">{settledRounds.map((round) => <article className="panel ledger-row" key={round.id}><div className="section-heading"><div><strong>{round.name}</strong><p>{round.occurredAt} · 已结算场次</p></div><strong className={tone(round.assetChangeCents)}>{formatB(round.assetChangeCents, true)}</strong></div><div className="ledger-grid"><span>投入<b>{formatB(round.stakeCents)}</b></span><span>毛结束金额<b>{formatB(round.grossResultCents)}</b></span><span>手续费<b>{formatB(round.feeCents)}</b></span><span>抽水<b>{formatB(round.rakeCents)}</b></span><span>结束所得<b>{formatB(round.settlementCents)}</b></span><span>资产变化<b className={tone(round.assetChangeCents)}>{formatB(round.assetChangeCents, true)}</b></span></div>{isAdmin && <button className="danger-button" onClick={() => { onTrash(round.id, '管理员删除'); setUndoRound(round); setNotice(`已删除${round.name}`); }}>删除</button>}</article>)}</div>
    {isAdmin && showTrash && <section className="panel trash-panel"><div className="section-heading"><h2>回收站</h2><button className="chip" onClick={() => setShowTrash(false)}>收起</button></div>{trashedRounds.length === 0 ? <p className="hint">回收站为空。</p> : trashedRounds.map((round) => <article className="trash-row" key={round.id}><strong>{roundName(round)}</strong><p>{round.occurredAt} · 操作者 {workspace.members.find((member) => member.id === round.deletedBy)?.name ?? round.deletedBy}</p><p>原因：{round.deleteReason}</p><div className="trash-actions"><button className="chip" onClick={() => { onRestore(round.id); setNotice('场次已恢复，并重新参与全部计算。'); }}>恢复场次</button><button className="danger-button compact" onClick={() => setPurgeTarget(round)}>永久删除</button></div></article>)}</section>}
    {purgeTarget && <section className="modal-backdrop" role="dialog" aria-modal="true"><div className="modal-card"><h2>确认永久删除该场次？</h2><p>此操作会清除该场次的模拟结算明细；仅保留不含金额详情的管理员操作日志，且不能恢复。</p><label className="input-label">输入“{roundName(purgeTarget)}”确认<input value={typedName} onChange={(event) => setTypedName(event.target.value)} placeholder={roundName(purgeTarget)} /></label><div className="modal-actions"><button className="chip" onClick={() => { setPurgeTarget(null); setTypedName(''); }}>取消</button><button className="danger-button" onClick={confirmPurge}>确认永久删除</button></div></div></section>}
    {rejectTarget && <section className="modal-backdrop" role="dialog" aria-modal="true"><div className="modal-card"><h2>拒绝这笔取回申请？</h2><p>{workspace.members.find((m) => m.id === rejectTarget.memberId)?.name} 申请取回 {formatB(rejectTarget.amountCents)}。拒绝后锁定的资金将退回其可用余额，成员的申请记录会显示拒绝状态和原因。</p><label className="input-label">拒绝原因（可留空）<input value={rejectReason} onChange={(event) => setRejectReason(event.target.value)} placeholder="例如：账目核对未通过" /></label><div className="modal-actions"><button className="chip" onClick={() => setRejectTarget(null)}>取消</button><button className="danger-button" onClick={() => { const name = workspace.members.find((m) => m.id === rejectTarget.memberId)?.name ?? ''; try { onReviewReturn(rejectTarget.id, false, rejectReason); setNotice(`已拒绝${name}的取回申请，资金已退回其可用余额。`); setRejectTarget(null); } catch { setNotice('拒绝失败，请稍后重试。'); } }}>确认拒绝</button></div></div></section>}
    {isAdmin && <section className="panel"><h2>全体范围</h2><p className="hint">当前模拟成员：{workspace.members.map((member) => member.name).join('、')}。正式环境必须由服务端按角色过滤查询结果，不能下载全体账本后只隐藏页面。</p></section>}{notice && <p className="notice toast-notice">{notice}{undoRound && <button className="chip" onClick={() => { onRestore(undoRound.id); setNotice(`已恢复${undoRound.name}`); setUndoRound(null); }}>撤销</button>}</p>}
  </main>;
}
